services:
  mysql:
    image: mysql:8.0
    container_name: aquacare-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: aquacare
      MYSQL_USER: aquacare
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - aquacare-data:/var/lib/mysql

volumes:
  aquacare-data: